repos:
  - repo: local
    hooks:
      - id: deno-fmt
        name: Deno Format
        entry: deno fmt
        language: system
        files: \.(js|jsx|ts|tsx|json|md)$
      - id: deno-lint
        name: Deno Lint
        entry: deno lint
        language: system
        files: \.(js|jsx|ts|tsx)$
