repos:
  - repo: local
    hooks:
      - id: deno-fmt
        name: Deno Format
        entry: deno fmt
        language: system
        files: \.(js|jsx|ts|tsx|json|md)$
        exclude: src/lib/parkrun/events\.json
      - id: deno-lint
        name: Deno Lint
        entry: deno lint
        language: system
        files: \.(js|jsx|ts|tsx)$
      - id: deno-check
        name: Deno Check
        entry: deno check src/index.tsx
        language: system
        pass_filenames: false
        always_run: true
