name: Build & Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Update events data
        run: curl -sSL https://images.parkrun.com/events.json -o src/lib/parkrun/events.json
      - name: Commit events.json if changed
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update parkrun events data"
          file_pattern: src/lib/parkrun/events.json

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: update-events
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Download data
        env:
          PARKRUN_ATHLETE_ID: ${{ secrets.PARKRUN_ATHLETE_ID }}
          PARKRUN_PASSWORD: ${{ secrets.PARKRUN_PASSWORD }}
          PARKRUN_CLIENT_ID: ${{ secrets.PARKRUN_CLIENT_ID }}
          PARKRUN_CLIENT_SECRET: ${{ secrets.PARKRUN_CLIENT_SECRET }}
        run: deno task download
      - name: Build
        run: deno task build
      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: deno deploy --org vlcdn --app parkruns --prod --no-wait dist
